---
apiVersion: batch/v1
kind: Job
metadata:
  name: metric-client
spec:
  template:
    metadata:
      name: metric-client
    spec:
      restartPolicy: Never
      containers:
        - name: metric-client
          image: journeycode/kubernetes:latest
          resources:
            limits:
              cpu: 100m
          env:
            - name: config
              value: ''
